113 토론 컨트롤러 개발
Eagle-Strike-7/stelligence-backend pull request #118
Opened 2024-01-27 16:40 UTC by youngandmini

## 변경 내용 

- 토론 / 댓글 엔티티가 추가되었습니다.
- 토론 컨트롤러와 응답 DTO가 추가되었습니다.
- 토론에 대한 댓글 컨트롤러와 요청/응답 DTO가 추가되었습니다.

## 특이 사항

- 피그마 상에 댓글은 페이징이 적용되지 않아 적용하지 않았습니다.
- 댓글을 토론 상세 조회에서 함께 반환하도록 하였습니다.
  - 페이징이 필요없을 것 같아서 이렇게 작성하였는데, 분리의 필요성이 있을 것 같다면 피드백 주시면 분리하겠습니다.
- 댓글 작성자를 commenter로 명명하였습니다.
  - author로 하면 글 최초 작성자와 헷갈릴 수도 있을 것 같아서 구분되는 변수명을 사용하였습니다.
  - 조금 이상한 것 같다면 피드백 부탁드립니다! 
- 토론의 종료 시간을 응답에 포함시켜주는 것이 좋을까요?
  - 토론의 시작시간만 응답에 포함하고 프론트에서 종료시간을 계산하라고 하면, 프론트엔드에서 "토론 지속시간"이라는 도메인에 의존하게 되어, 토론 지속시간의 변경에 프론트 코드도 변경되는 단점이 있을 것 같습니다.

## 체크리스트

- [x] PR 날리기 전에 main branch pull 받으셨나요?
- [x] application.properties 등 노출되지 않아야 하는 파일이 올라가지는 않았나요?
- [x] 다른 담당자 파일을 수정한 부분에 대해서 이야기 하셨나요?
- [x] 주석 "상세히" 다셨나요?
- [x] 제출하기 전에 테스트코드 돌려 보셨나요?

closes #

2024-01-28 03:25 UTC, sbslc2000 approved these changes
깔끔 그 자체네요

2024-01-28 03:25 UTC, sbslc2000 commented on src/main/java/goorm/eagle7/stelligence/domain/debate/DebateController.java
> +	)
여기 Description에 토론 종료가 유효하게 작동하는 조건? ex) (토론의 상태가 OPEN이어야 하고 오직 수정요청을 생성한 사람만이 종료할 수 있다) 요런거 추가해보면 어떨까요?

2024-01-28 03:26 UTC, sbslc2000 commented
종료(예정)시간은 백엔드에서 관리하는게 좋아보이긴 하네요. 이 요구사항은 구체적인게 없는걸로 알고 있는데 맞을까요?

2024-01-28 05:13 UTC, youngandmini commented on src/main/java/goorm/eagle7/stelligence/domain/debate/DebateController.java
> +	)
좋습니다!! 같이 추가해주어야 클라이언트도 확실하게 알수 있을 것 같네요

2024-01-28 05:15 UTC, youngandmini commented
> 종료(예정)시간은 백엔드에서 관리하는게 좋아보이긴 하네요. 이 요구사항은 구체적인게 없는걸로 알고 있는데 맞을까요?

네네 아직은 확실하게 정해진 것은 없었습니다
이를 애플리케이션 단에서 관리할지,(createdAt에 토론 지속 시간을 더해서 계산)
DB 단에서 관리할지,(DB에 저장할 때 endAt을 계산하여 저장해둠)
도 고려해서 결정해야할 것 같습니다!!

2024-01-29 03:50 UTC, Sooamazing approved these changes
페이지 참고하겠습니다,,^_^!!!!!

2024-01-29 06:03 UTC, eenzzi requested changes
endAt 추가해서 다시 올리세요!!!!!!1

2024-01-30 13:01 UTC, sbslc2000 reviewed
깔끔 그 자체네요. DTO 생성자 혹은 생성 메서드는 일부러 작성 안하신건가요?

2024-01-30 13:01 UTC, sbslc2000 commented on src/main/java/goorm/eagle7/stelligence/domain/debate/DebateController.java
> +		@RequestParam("order") CommentOrderCondition order
요고 기본값 주면 어떨까요?

2024-01-30 13:31 UTC, youngandmini commented on src/main/java/goorm/eagle7/stelligence/domain/debate/dto/DebatePageResponse.java
> +public class DebatePageResponse {
Page에 불필요한 정보가 너무 많아서 필요한 정보만 넘겨주자는 생각도 있었고,
실제 토론 리스트의 변수명이 content로 고정되는게 조금 싫었습니다!

2024-01-30 13:33 UTC, youngandmini commented on src/main/java/goorm/eagle7/stelligence/domain/debate/DebateController.java
> +		@RequestParam("order") CommentOrderCondition order
일반적으로는 등록순으로 보는게 토론의 흐름을 쭉 보기 좋을테니, 등록순으로 정렬하는 것을 기본값으로 주는 것이 좋겠네요 bb 조언 감사합니다!!

2024-01-30 13:49 UTC, youngandmini commented
> 깔끔 그 자체네요. DTO 생성자 혹은 생성 메서드는 일부러 작성 안하신건가요?

아직 사용을 안해서 작성 안했는데, 미리 추가해두는 게 나을까요?

2024-01-30 14:17 UTC, sbslc2000 commented on src/main/java/goorm/eagle7/stelligence/domain/debate/dto/DebatePageResponse.java
> +public class DebatePageResponse {
그럼 혹시 다른 곳에서는 Page를 쓰고 있는게 이거 통일 안해줘도 괜찮으려나요? content 맘에 안드는건 공감합니다 ㅋㅋ

2024-01-31 02:19 UTC, merged